# Makefile for P2R

dist: clean
	mkdir dist && tar czvf dist/urispace.tar.gz ../urispace/urispace.pl ../urispace/run.pl ../urispace/mapping.pl ../urispace/config.pl ../urispace/jamendo_mapping.pl ../urispace/log.pl ../urispace/Makefile ../urispace/gpl.txt

clean:
	rm -rdf dist/



