select ?tline ?key
where
{
<http://dbtune.org/audio/Den-Nostalia.ogg> <http://purl.org/ontology/mo/encodes> ?sig.
?sig mo:time [tl:timeline ?tline].
_:tonalregion event:time [tl:onTimeLine ?tline];
event:factor ?key

}



