# Makefile for P2R

dist: clean
	mkdir dist && tar czvf dist/p2r.tar.gz ../p2r/README ../p2r/Makefile ../p2r/sparql.pl ../p2r/http_sparql.pl ../p2r/p2r_entailment.pl ../p2r/match.pl ../p2r/rdf_compile.pl ../p2r/rdf_dump.pl ../p2r/run.pl ../p2r/examples/jamendo.pl ../p2r/examples/jamendo_ns.pl ../p2r/examples/jamendo_xml.pl ../p2r/examples/jamendo_match.pl ../p2r/examples/README ../p2r/gpl.txt

clean:
	rm -rdf dist/



